### ISSUE TITLE
As a user, I want to have an up-to-date dictionary dataset so that I can query terms

### ISSUE THREAD

**Issue by oflynned** [oflynned/Syzible#3]
User story:
As a user, I want to have an up-to-date dictionary dataset so that I can query terms

Acceptance criteria:
- [x] Implement database interactor layer #7 
- [x] Implement different environments (production, development, test) #9
- [x] Define noun schema #10
- [x] Download Tearma.ie datastore correctly #11
- [x] Parse noun data #12
- [x] Add linter to CI #16 
- [ ] Define verb schema 
- [ ] Parse verb data
- [ ] Define adjective schema
- [ ] Parse adjective data
- [ ] Define phrase schema
- [ ] Parse phrase data
- [ ] Log and manage Tearma.ie datastore entries from collection
- [ ] Run cron job run monthly to update the data-store

Definition of done:
- Datastore runs monthly
- Datastore is cleaned monthly
- Datastore follows a regular schema
